apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbo_app  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbo_app
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fbo_app
        role: fbo_app
    spec:
      containers:
        - name: fbo_app
          image: franmib/curso:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: fbo_app
​
---
apiVersion: v1
kind: Service
metadata:
  name: fbo_app
  labels:
    app: fbo_app
spec:
  selector:
   app: fbo_app
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: fbo_app