apiVersion: apps/v1
kind: Deployment
metadata:
  name: fboapp
  namespace: fbo2  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fboapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fboapp
        role: fboapp
    spec:
      containers:
        - name: fboapp
          image: franmib/curso:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: fboapp
---
apiVersion: v1
kind: Service
metadata:
  name: fboapp
  namespace: fbo2
  labels:
    app: fboapp
spec:
  selector:
   app: fboapp
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: fboapp