apiVersion: v1
kind: Namespace
metadata:
  name: fbo2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbomysql-data-disk
  namespace: fbo2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: fbomysql-secrets
  namespace: fbo2
type: Opaque
data:
  password: c3VwZXI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbomysql-deployment
  namespace: fbo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbomysql
  template:
    metadata:
      labels:
        app: fbomysql
    spec:
      containers:
        - name: fbomysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fbomysql-secrets
                  key: password
          ports:
            - containerPort: 3306
              name: fbomysql
          volumeMounts:
            - name: fbomysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: fbomysql-data
          persistentVolumeClaim:
            claimName: fbomysql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: fbomysql-service
  namespace: fbo2
spec:
  selector:
    app: fbomysql
  type: ClusterIP
  ports:
    - name: fbomysql
      port: 3306
      targetPort: 3306