apiVersion: v1
kind: Namespace
metadata:
  name: fbo
---
apiVersion: v1
kind: Secret
metadata:
  name: myKey
  namespace: fbo
type: Opaque
data:
  ROOT_PASSWORD: ZW5taW1hcXVpbmFzaWZ1bmNpb25h
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fboMySqlData
  namespace: fbo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fboMySqlPod
  namespace: fbo
  labels:
    app: fboMySqlPod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fboMySqlPod
  template:
    metadata:
      labels:
        app: fboMySqlPod
    spec:
      containers:
        - name: fboMySqlPod
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: fboMySqlData
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myKey
                  key: ROOT_PASSWORD
      volumes:
        - name: fboMySqlData
          persistentVolumeClaim:
            claimName: fboMySqlData
---
apiVersion: v1
kind: Service
metadata:
  name: fboMySqlService
  namespace: fbo
spec:
  selector:
    app: fboMySqlService
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306