apiVersion: v1
kind: Namespace
metadata:
  name: fbo
---
apiVersion: v1
kind: Secret
metadata:
  name: mykey
  namespace: fbo
type: Opaque
data:
  ROOT_PASSWORD: ZW5taW1hcXVpbmFzaWZ1bmNpb25h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbophpmyadmin
  namespace: fbo
  labels:
    app: fbophpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbophpmyadmin
  template:
    metadata:
      labels:
        app: fbophpmyadmin
    spec:
      containers:
        - name: fbophpmyadmin
          image: franmib/phpmyadmin:devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: fbomysqlservice
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mykey
                  key: ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: fbopma
  namespace: fbo
spec:
  type: ClusterIP
  selector:
    app: fbopma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
