apiVersion: v1
kind: Namespace
metadata:
  name: fbo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbophpmyadmin-deployment
  namespace: fbo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fbophpmyadmin
  template:
    metadata:
      labels:
        app: fbophpmyadmin
    spec:
      containers:
        - name: fbophpmyadmin
          image: franmib/phpmyadmin:devops
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: fbomysql-service
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fbomysql-secrets
                  key: password
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fbophpmyadmin-service
  namespace: fbo2
spec:
  type: ClusterIP
  selector:
    app: fbophpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80